### PR TITLE
small improvements

### PR DESCRIPTION
**Pull request by iurianu**

### CODE REVIEW

**Comment by claire-lovisa** [comment]
Hey ! Could you take a look at https://github.com/lblod/ember-environment-banner (Elena implemented it here in GN https://github.com/lblod/frontend-gelinkt-notuleren/pull/318 ) to see if that could be reused ? We try to use as much common code as possible across lblod projects. You'll probably need to extend `ember-environment-banner` to be able to configure the color

**Comment by nbittich** [comment]
@iurianu could you try with the component proposed by @claire-lovisa  ? thxx

**Review by nbittich — COMMENTED** [review]
see comment of claire

**Comment by iurianu** [comment]
> @iurianu could you try with the component proposed by @claire-lovisa ? thxx

I'm working on it now. I've spoken to Elena, and she told me how to customize the variables for the banner!

**Review by nbittich — APPROVED** [review]
nice!

**Pull request merged**
