### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by iurianu**
OP-1856 | OP-1859

### CODE REVIEW

**Comment by nbittich** [comment]
Are you sure this implements OP-1839?  it doesn't seem so

**Comment by iurianu** [comment]
> Are you sure this implements OP-1839? it doesn't seem so

The branch was created for Op-1839, and while working on it, I found the bug in OP-1859

**Comment by claire-lovisa** [comment]
So this PR is only for OP-1859 and a new PR will be created for OP-1839 ?

**Review by claire-lovisa — APPROVED** [review]
Approving after a discussion during the standup about this PR being only for OP-1859. @iurianu can you change the title and description of this PR so that it really reflects what it's doing ? Thanks ! :)

**Pull request merged**
