### PR TITLE
Disable validation on planned end date

### PR DESCRIPTION
**Pull request by claire-lovisa**
OP-2668

### CODE REVIEW

**Comment by lagartoverde** [comment]
Even if we disable that is a required field, shouldn't we keep the validateFutureDate, so in case any date gets input it checks it's not a past date?

**Comment by claire-lovisa** [comment]
> Even if we disable that is a required field, shouldn't we keep the validateFutureDate, so in case any date gets input it checks it's not a past date?

Ooooh yes you're completely right !! Gonna fix it

**Comment by claire-lovisa** [comment]
@lagartoverde Ready to be re-reviewed :)

**Review by lagartoverde — APPROVED** [review]
Looks good to me :)

**Pull request merged**
