### PR TITLE
Change events - IGS

### PR DESCRIPTION
**Pull request by claire-lovisa**
OP-2514

### CODE REVIEW

**Review by lagartoverde — APPROVED** [review]
I was thinking, that maybe we should export the check of isIGS to an utility function, as we are repeating that piece of code everywhere

**Comment by claire-lovisa** [comment]
We could, but I'm not sure it would be that easy cause we have slightly different ways of checking it depending on how the model is structured etc :thinking:

**Comment by lagartoverde** [comment]
Yes, I was thinking more like `isIGS(classificationId)`

**Comment by claire-lovisa** [comment]
Feel free to add it :grin:

**Pull request merged**
